version: 1.2
workflows:
  - name: projected_PCA
    subclass: WDL
    primaryDescriptorPath: /projected_pca.wdl
    authors: 
      - orcid: 0000-0002-7989-5420
    testParameterFiles:
       - /projected_pca.json
  - name: create_pca_projection
    subclass: WDL
    primaryDescriptorPath: /create_pca_projection.wdl
    authors: 
      - orcid: 0000-0002-7989-5420
    testParameterFiles:
       - /create_pca_projection.json
  - name: LD_pruning
    subclass: WDL
    primaryDescriptorPath: /ld_pruning.wdl
    testParameterFiles:
       - /ld_pruning.json
  - name: select_variants_by_pop_maf
    subclass: WDL
    primaryDescriptorPath: /maf_by_pop.wdl
    testParameterFiles:
       - /maf_by_pop.json
       