name: Womtool

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "main" ]
    paths-ignore: [ "docs/**" ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  run-womtool:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        wdl-file: [
          create_pca_projection.wdl,
          file_tasks.wdl,
          ld_pruning.wdl,
          maf_by_pop.wdl,
          pca_plots.wdl,
          pca_tasks.wdl,
          projected_pca.wdl,
          sample_filtering.wdl,
          variant_filtering.wdl
        ]

    name: "Run womtool: ${{ matrix.wdl-file }}"

    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Run womtool
        uses: UW-GAC/womtool-action@main
        with:
            wdl-file: ${{ matrix.wdl-file }}
